[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
fs_permissions = [{ access = "read-write", path = "./deployments/"}]
gas_reports = ["CollateralAgreementFramework", "Arbitrator"]
